language: python

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.conda
        - $TRAVIS_BUILD_DIR/testdata

python:
    - 2.7
    - 3.4

env:
    - NUMPY_VERSION=1.10.2 OMP_NUM_THREADS=1

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - conda install --yes numpy=$NUMPY_VERSION nose mpi4py scipy h5py cython
    - pip install kdcount bigfile runtests
    - pip install fitsio
    - python setup.py install

before_script:
    - if ! [ -d testdata/dr3-mini ]; then
      mkdir -p testdata;
      pushd testdata;
      curl https://s3-us-west-1.amazonaws.com/imaginglss/SFD98.tar.gz | tar -xz;
      curl https://s3-us-west-1.amazonaws.com/imaginglss/tycho2.tar.gz | tar -xz;
      curl -O https://s3-us-west-1.amazonaws.com/imaginglss/WISE-BRIGHT.hdf5;
      curl https://s3-us-west-1.amazonaws.com/imaginglss/dr3-mini.tar.gz | tar -xz;
      ls testdata ;
      ls testdata/dr3-mini;
      popd ;
      fi

script: 
    - bash runtests.sh
